# Generated by Django 4.0.4 on 2022-09-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_created_at_alter_activity_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImcCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weigth', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
    ]
