# Generated by Django 4.0.4 on 2022-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imccalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='imccalculation',
            name='imc',
            field=models.FloatField(default=0),
        ),
    ]
