# Generated by Django 4.0.4 on 2022-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imccalculation_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imccalculation',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='imccalculation',
            name='weigth',
            field=models.FloatField(default=0.0),
        ),
    ]
