# Generated by Django 4.0.4 on 2022-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_imccalculation_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imccalculation',
            name='imc',
        ),
    ]
