# Generated by Django 4.0.4 on 2022-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_imccalculation_imc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imccalculation',
            old_name='weigth',
            new_name='weight',
        ),
    ]
